import type { Metadata } from "next";
import { Inter, Protest_Strike } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/organisms/navbar/Navbar";
import Footer from "@/components/organisms/footer/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const protestStrike = Protest_Strike({
  weight: "400",
  variable: "--font-protest-strike",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Okorok",
    template: "%s - Okorok",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${protestStrike.variable} antialiased font-inter`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
